"""Verify Video Studio module V1 foundation."""
import sys, paramiko
try: sys.stdout.reconfigure(encoding="utf-8", errors="replace")
except: pass
HOST = "103.82.193.74"
PASSWORD = sys.argv[1] if len(sys.argv) > 1 else ""

CMD = r"""
cd /opt/vp-marketing
cat > /opt/vp-marketing/_tmp_vs.js <<'JS'
process.chdir('/opt/vp-marketing');
const Database = require('better-sqlite3');
const db = new Database('data/db.sqlite');

console.log('=== Check tables ===');
const tables = db.prepare(`SELECT name FROM sqlite_master WHERE type='table' AND name LIKE 'video_%' ORDER BY name`).all();
console.log(`Found ${tables.length} video_* tables:`);
for (const t of tables) console.log(`  ${t.name}`);

console.log('\n=== Test 1: Enable module + create default brand kit ===');
const { setSetting } = require('/opt/vp-marketing/dist/db');
setSetting('video_studio_enabled', 'true');

const { isVideoStudioEnabled } = require('/opt/vp-marketing/dist/services/video-studio/feature-flag');
console.log(`isVideoStudioEnabled: ${isVideoStudioEnabled()}`);

const { ensureDefaultBrandKit } = require('/opt/vp-marketing/dist/services/video-studio/brand-kit');
const kit = ensureDefaultBrandKit();
console.log(`Brand kit: id=${kit.id} created=${kit.created} name=${kit.brand_kit.name}`);
console.log(`  LUT file: ${kit.brand_kit.color_lut_file}`);
console.log(`  Aspect: ${kit.brand_kit.aspect_ratio} (${kit.brand_kit.resolution})`);

// Verify LUT file exists
const fs = require('fs');
if (kit.brand_kit.color_lut_file && fs.existsSync(kit.brand_kit.color_lut_file)) {
  const sz = fs.statSync(kit.brand_kit.color_lut_file).size;
  console.log(`  LUT file exists: ${sz} bytes`);
} else {
  console.log(`  LUT file MISSING`);
}

console.log('\n=== Test 2: Content discovery (AI brainstorm) ===');
(async () => {
  const { brainstormTopicsViaAI, listUnusedIdeas } = require('/opt/vp-marketing/dist/services/video-studio/content-discovery');
  const ideas = await brainstormTopicsViaAI(3);
  console.log(`AI generated ${ideas.length} ideas:`);
  for (const i of ideas) {
    console.log(`  - ${i.topic} (score=${i.relevance_score.toFixed(2)}, ${i.seasonal_tag})`);
  }

  // Insert for later test
  for (const i of ideas) {
    db.prepare(`
      INSERT OR IGNORE INTO video_content_ideas
        (topic, description, source_type, relevance_score, trending_score, seasonal_tag, discovered_at)
      VALUES (?, ?, 'ai_generated', ?, ?, ?, ?)
    `).run(i.topic, i.description || null, i.relevance_score, i.trending_score, i.seasonal_tag, i.discovered_at);
  }

  const unused = listUnusedIdeas(5);
  console.log(`\n  Unused ideas in library: ${unused.length}`);

  console.log('\n=== Test 3: Script writer ===');
  const { generateScript, estimateTTSCost } = require('/opt/vp-marketing/dist/services/video-studio/script-writer');
  const testTopic = '5 mẹo đặt vé máy bay rẻ ít ai biết';
  const script = await generateScript({
    topic: testTopic,
    target_duration_sec: 90,
    style: 'warm',
    audience: 'du khách trẻ 20-35',
  });

  if (!script) {
    console.log('  ❌ Script generation failed');
    return;
  }

  console.log(`  ✅ Script generated by ${script.provider}`);
  console.log(`  Title: ${script.title}`);
  console.log(`  Hook: ${script.hook_question}`);
  console.log(`  Total duration: ${script.total_duration_sec}s`);
  console.log(`  Scenes: ${script.scenes.length}`);
  for (const s of script.scenes.slice(0, 3)) {
    console.log(`    [${s.kind}] ${s.duration_sec}s: "${s.text.substring(0, 60)}..."`);
    console.log(`      visual: "${s.visual_prompt.substring(0, 80)}..."`);
    console.log(`      keywords: ${s.stock_keywords.join(', ')}`);
  }
  console.log(`  CTA: ${script.cta_text}`);
  console.log(`  Caption: ${script.caption_social}`);
  console.log(`  Hashtags: ${script.hashtags.join(' ')}`);

  const ttsCost = estimateTTSCost(script);
  console.log(`  Estimated TTS cost: ${ttsCost.chars} chars → $${(ttsCost.elevenlabs_cents / 100).toFixed(3)}`);

  console.log('\n=== Test 4: Create project + orchestrator flow ===');
  const { createProject, generateScriptStep, getProject, getProjectScenes } =
    require('/opt/vp-marketing/dist/services/video-studio/studio-orchestrator');

  // Clean previous test projects
  db.prepare(`DELETE FROM video_scenes WHERE project_id IN (SELECT id FROM video_projects WHERE topic LIKE 'TEST: %')`).run();
  db.prepare(`DELETE FROM video_cost_ledger WHERE project_id IN (SELECT id FROM video_projects WHERE topic LIKE 'TEST: %')`).run();
  db.prepare(`DELETE FROM video_projects WHERE topic LIKE 'TEST: %'`).run();

  const createR = createProject({
    topic: 'TEST: ' + testTopic,
    target_duration_sec: 90,
    tier: 'stock',
    generated_by: 'verify@test',
  });
  if ('error' in createR) { console.log(`  ❌ Create failed: ${createR.error}`); return; }
  console.log(`  ✅ Project created id=${createR.id} status=${createR.project.status}`);

  console.log('  Running generateScriptStep...');
  const scriptR = await generateScriptStep(createR.id);
  console.log(`  generateScriptStep: ${JSON.stringify(scriptR)}`);

  const updatedProj = getProject(createR.id);
  console.log(`  Status after script: ${updatedProj?.status}`);
  console.log(`  Cost so far: $${((updatedProj?.cost_cents || 0) / 100).toFixed(3)}`);

  const scenes = getProjectScenes(createR.id);
  console.log(`  Scenes persisted: ${scenes.length}`);

  // Cleanup
  db.prepare(`DELETE FROM video_scenes WHERE project_id = ?`).run(createR.id);
  db.prepare(`DELETE FROM video_cost_ledger WHERE project_id = ?`).run(createR.id);
  db.prepare(`DELETE FROM video_projects WHERE id = ?`).run(createR.id);

  console.log('\n=== Test 5: Pexels stock fetch (requires PEXELS_API_KEY) ===');
  const { searchPexels } = require('/opt/vp-marketing/dist/services/video-studio/providers/pexels');
  const clips = await searchPexels('vietnamese street food', { orientation: 'portrait', perPage: 3 });
  console.log(`  Pexels returned ${clips.length} clips`);
  if (clips.length === 0) {
    console.log('  (No PEXELS_API_KEY set, test skipped — configure via /video-studio → Settings)');
  } else {
    for (const c of clips) console.log(`    ${c.clip_url.substring(0, 80)}... (${c.duration_sec}s ${c.width}x${c.height})`);
  }

  // Cleanup settings (leave module ON for user)
  db.close();
  console.log('\n✅ Video Studio V1 foundation verified');
})().catch(e => { console.error('Fatal:', e); process.exit(1); });
JS

node /opt/vp-marketing/_tmp_vs.js
rm /opt/vp-marketing/_tmp_vs.js
"""

c = paramiko.SSHClient()
c.set_missing_host_key_policy(paramiko.AutoAddPolicy())
c.connect(HOST, username="root", password=PASSWORD, timeout=20)
_, out, err = c.exec_command(CMD, timeout=180)
print(out.read().decode('utf-8', errors='replace'))
e = err.read().decode('utf-8', errors='replace')
if e.strip(): print('--STDERR--'); print(e)
c.close()
